namespace: "simeononsecurity"
name: "windows_stigs"
description: "Ansible Playbooks for SimeonOnSecurity's STIG Scripts"
version: "1.1.0"
readme: "README.md"
homepage: "https://simeononsecurity.ch"
issues: "https://github.com/simeononsecurity/Windows_STIG_Ansible/issues"
repository: "https://github.com/simeononsecurity/Windows_STIG_Ansible"
authors:
    - "SimeonOnSecurity (https://simeononsecurity.ch)"
dependencies:
    "ansible.windows": "*"
    "community.windows": "*"
    "community.general": "*"
license_file: LICENSE
tags:
    - collection
    - windows
    - chocolatey
    - package
build_ignore:
- collections/ansible_collections/general*
- .github
- .gitattributes
- .gitignore