---
# tasks file for base

- name: check if python is already installed
  ansible.windows.win_powershell:
    script: python

- name: Installing python using Chocolatey
  chocolatey.chocolatey.win_chocolatey:
    name: python
    state: present
    version: latest
    allow_empty_checksums: yes

- name: Download Github Repo "{{ gitrepo }}"
  ansible.builtin.git:
    repo: "{{ gitrepo }}"
    dest: "{{ gitdir }}"
  environment:
    GIT_TERMINAL_PROMPT: 0

- name: Run PowerShell script that modifies the module changed result
  ansible.windows.win_powershell:
    chdir: "{{ gitdir }}"
    script: |
      try{
      
        powershell.exe -ExecutionPolicy ByPass -File "{{ gitdir }}"/*.ps1

      } Catch {

        $Ansible.failed = $true

      }  

- name: Uninstall python using Chocolatey
  chocolatey.chocolatey.win_chocolatey:
    name: python
    state: absent