---
# tasks file for base

- name: Debug VARs
  ansible.builtin.debug:
    msg: "Gitrepo is {{ gitrepo }}"
  ansible.builtin.debug:
    msg: "Gitdir is {{ gitdir }}"
  ansible.builtin.debug:
    msg: "Gitname is {{ gitname }}"
  ansible.builtin.debug:
    msg: "Zipdir is {{ ziprepo }}"

- name: Download STIG files to specified path
  ansible.windows.win_get_url:
    url: "{{ gitrepo }}"
    dest: "{{ gitdir }}"
    follow_redirects: all
    force: yes

- name: Fix Windows Path Character Limit
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem
    name: LongPathsEnabled
    data: 1
    type: dword

# Unzip STIG .zip file, recursively decompresses the contained zips and removes all unneeded compressed files after completion.
- name: Recursively decompress zip files
  community.windows.win_unzip:
    src: "{{ gitdir }}"
    dest: "{{ zipdir }}"
    recurse: yes
    delete_archive: yes

- name: Run the STIG Script
  ansible.windows.win_powershell:
    chdir: "{{ gitdir }}"
    script: |
      try{
      
        powershell.exe -ExecutionPolicy ByPass -File "{{ zipdir }}/*.ps1"

      } Catch {

        $Ansible.failed = $true

      }  