---
# vars file for base
gitrepo: "https://github.com/simeononsecurity/.NET-STIG-Script/archive/refs/heads/master.zip"
gitdir: "C:\\temp\\master.zip"
gitname: ".NET-STIG-Script"
zipdir: "C:\\temp\\{{ gitname }}"