---
# vars file for base
gitrepo:
  - "https://github.com/simeononsecurity/FireFox-STIG-Script/archive/refs/heads/master.zip"
gitdir:
  - "{{ ansible_env.TEMP }}\\master.zip"
gitname:
  - "FireFox-STIG-Script"
zipdir:
  - "{{ ansible_env.TEMP }}\\{{ gitname }}"