namespace: "simeononsecurity"
name: "Windows_STIG_Ansible"
description: "Ansible Playbooks for SimeonOnSecurity's STIG Scripts"
version: "1.0.0"
readme: "README.md"
homepage:
    - "https://simeononsecurity.ch"
issues:
    - "https://github.com/simeononsecurity/Windows_STIG_Ansible/issues"
authors:
    - "SimeonOnSecurity (https://simeononsecurity.ch)"
dependencies:
    "chocolatey.chocolatey": "*"
    "ansible.windows": "*"
    "community.windows": "*"
license:
    - "GPLv3"
license_file: 
    - LICENSE
tags:
    - collection
    - windows
    - chocolatey
    - package
repository: "https://github.com/simeononsecurity/Windows_STIG_Ansible"